services:
  - type: web
    name: bokoma-stor
    env: python
    region: frankfurt        # ou 'oregon' si tu veux un serveur US
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --workers 1 -b 0.0.0.0:$PORT run:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true    # Render génère une clé aléatoire sécurisée
      - key: DATABASE_URL
        fromDatabase:
          name: bokoma-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        generateValue: true    # Change via Render dashboard après 1er déploiement

    # Optionnel : domaine personnalisé
        domains:
         - domain: www.bokoma-stor.com
         - domain: bokoma-stor.com

databases:
  - name: bokoma-db
    databaseName: bokoma_stor_db
    user: bokoma_user
    region: frankfurt

runtime: python3.11
