services:
  - type: web
    name: bokoma-stor
    env: python
    region: frankfurt
    runtime: python:3.11  # ‚Üê OBLIGATOIRE
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "gunicorn --workers 1 -b 0.0.0.0:$PORT run:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: bokoma-db
          property: connectionString
      - key: ADMIN_USERNAME
        value: "admin"
      - key: ADMIN_PASSWORD
        generateValue: true

databases:
  - name: bokoma-db
    databaseName: bokoma_stor_db
    user: bokoma_user
    region: frankfurt